import asyncio
from datetime import datetime
from typing import Any, Dict, List, Optional

from backend.browser_controller import BrowserController
from backend.llm_interface import OllamaLLM
from backend.utils import save_log
from backend.vision_module import VisionModule


class AgentExecutor:
    """Executes browser automation plans generated by the LLM."""

    def __init__(
        self,
        browser_controller: BrowserController,
        llm: OllamaLLM,
        vision: Optional[VisionModule] = None,
    ):
        self.browser_controller = browser_controller
        self.llm = llm
        self.vision = vision
        self.history: List[Dict[str, Any]] = []
        self._lock = asyncio.Lock()

    async def run_instruction(self, instruction: str) -> Dict[str, Any]:
        async with self._lock:
            plan = await self.llm.generate_plan(instruction)
            # Add heuristic click if needed
            plan = self._add_heuristic_click(instruction, plan)
            logs: List[Dict[str, Any]] = []
            successful = True

            save_log(f"Generated plan: {plan}")

            for index, step in enumerate(plan, start=1):
                log_entry = {
                    "step_number": index,
                    "action": step.get("action"),
                    "raw": step,
                }
                try:
                    save_log(f"Executing step #{index}: {step}")
                    result = await self.execute_step(step)
                    log_entry["result"] = result
                    log_entry["status"] = "ok"
                    save_log(f"Step #{index} success: {result}")
                except Exception as exc:
                    successful = False
                    log_entry["error"] = str(exc)
                    log_entry["status"] = "error"
                    save_log(f"Step #{index} failed: {exc}")
                    if self.vision:
                        fallback = await self._recover_with_vision(step)
                        if fallback:
                            log_entry["vision_hint"] = fallback
                    logs.append(log_entry)
                    break

                logs.append(log_entry)

            record = {
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "instruction": instruction,
                "plan": plan,
                "logs": logs,
                "success": successful,
            }
            self.history.insert(0, record)
            return {
                "success": successful,
                "plan": plan,
                "logs": logs,
                "history_count": len(self.history),
            }

    def _add_heuristic_click(self, instruction: str, plan: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Add a click step if instruction implies selecting first result."""
        keywords = ["first video", "open first result", "click first result", "first search result"]
        if any(kw in instruction.lower() for kw in keywords):
            # Determine site and selector
            for step in plan:
                if step.get("action") == "open_url":
                    url = step.get("value", "").lower()
                    if "youtube.com" in url:
                        plan.append({"action": "click", "selector": "ytd-video-renderer a#thumbnail"})
                    elif "google.com" in url:
                        plan.append({"action": "click", "selector": "h3"})
                    elif "amazon.com" in url:
                        plan.append({"action": "click", "selector": "div.s-main-slot a"})
                    break
        return plan

    async def execute_step(self, step: Dict[str, Any]) -> Dict[str, Any]:
        action = str(step.get("action", "")).lower()
        if action == "open_url":
            return await self.browser_controller.open_url(str(step["value"]))
        if action == "click":
            result = await self.browser_controller.click(str(step["selector"]))
            save_log(f"Click method: {result.get('method', 'unknown')}")
            return result
        if action == "type":
            return await self.browser_controller.type(str(step["selector"]), str(step.get("value", "")))
        if action == "press":
            return await self.browser_controller.press(str(step["key"]))
        if action == "scroll":
            direction = str(step.get("direction", "down"))
            amount = int(step.get("amount", 300))
            return await self.browser_controller.scroll(direction=direction, amount=amount)
        if action == "wait":
            return await self.browser_controller.wait(float(step.get("seconds", 1)))
        if action == "screenshot":
            path = step.get("value", "page.png")
            screenshot_path = await self.browser_controller.screenshot(path=str(path))
            return {"action": "screenshot", "path": screenshot_path}
        if action == "find_clickable":
            return await self._find_clickable_elements()
        if action == "navigate_back":
            return await self.browser_controller.navigate_back()
        if action == "navigate_forward":
            return await self.browser_controller.navigate_forward()

        raise ValueError(f"Unsupported action type: {action}")

    async def _find_clickable_elements(self) -> Dict[str, Any]:
        if self.vision is None:
            raise RuntimeError("Vision module is unavailable.")

        screenshot_path = await self.browser_controller.screenshot()
        description = await self.vision.describe_screen(
            screenshot_path,
            "List the clickable elements visible in this browser screenshot with a short text summary.",
        )
        return {"action": "find_clickable", "description": description}

    async def _recover_with_vision(self, step: Dict[str, Any]) -> Optional[str]:
        if self.vision is None:
            return None

        try:
            screenshot_path = await self.browser_controller.screenshot()
            description = await self.vision.describe_screen(
                screenshot_path,
                f"A browser automation step failed: {step}. What clickable elements can you see on the screen?",
            )
            return description
        except Exception as exc:
            save_log(f"Vision recovery failed: {exc}")
            return None
